# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.3.0
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/android:api-28-alpha
      # mono for desktop......
      #- image: mono:latest

    working_directory: ~/repo

    steps:
      - checkout
  test:  
    docker:
      - image: circleci/node
      - image: circleci/android
    working_directory: ~/repo/Mobile/Fennec

    steps:
      - run: npm install
      - run: npm install tns
      - run: tns test init --framework mocha
      - run: tns test android
      - run: tns test ios
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          - build